services:
  kener:
    image: rajnandan1/kener:latest 
    container_name: kener
    #env_file: .env #uncomment this, if you are using .env file
    environment:
      - TZ=Etc/UTC
      #- GH_TOKEN=
      #- API_TOKEN=
      #- API_IP=
      #- API_IP_REGEX=
      #- KENER_BASE_PATH=

      # If running on a LINUX HOST and not podman rootless these MUST BE SET
      # run "id $user" from command line and replace numbers below with output from command
      #- PUID=1000 # gid
      #- PGID=1000 # uid

      ### Most likely DO NOT need to change anything below this ###

      #- PORT=3000 Port app listens on IN CONTAINER
    ports:
      - '3000:3000/tcp'
    volumes:
      - './database:/app/database:rw'
      - './config:/app/config'
