apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: status-page
  description: Statuspage monitoring of Heimdall and Heimdall Services
  tags:
    - statuspage
  annotations:
    backstage.io/source-location: url:https://github.com/NovoNordisk-OpenSource/kener/
spec:
  type: service
  lifecycle: production
  owner: heimdall-team
  domain: heimdall