### PROD 
- name: Bifrost Grafana
  description: Bifrost Grafana
  tag: "bifrost-grafana"
  image: "/grafana.png"
  cron: "* * * * *"
  defaultStatus: "UP"
  api:
    timeout: 4000
    method: GET
    url: https://bifrost.heimdall.novonordisk.cloud/health/grafana
    eval: |
        (function(statusCode, responseTime, responseDataBase64){
        console.log(statusCode)
        return {
            status: statusCode == 200 ? 'UP':'DOWN',
            latency: responseTime,
        }
        })

- name: Bifrost OpenTelemetry
  description: Bifrost Open Telemetry collector for PRD
  tag: "bifrost-otel"
  image: "/otel.png"
  cron: "* * * * *"
  defaultStatus: "UP"
  api:
    timeout: 4000
    method: GET
    url: https://bifrost.heimdall.novonordisk.cloud/health/otlp/http
    eval: |
        (function(statusCode, responseTime, responseDataBase64){
        console.log(statusCode)
        return {
            status: statusCode == 200 ? 'UP':'DOWN',
            latency: responseTime,
        }
        })

- name: Developer Portal - Midgard
  description: The Developer Portal Midgard UI
  tag: "midgard-ui"
  image: "/midgardlogo.png"
  cron: "* * * * *"
  defaultStatus: "UP"
  api:
    timeout: 4000
    method: GET
    url: https://midgard.heimdall.novonordisk.cloud/.backstage/health/v1/liveness
    eval: |
        (function(statusCode, responseTime, responseDataBase64){
        console.log(statusCode)
        const resp = JSON.parse(atob(responseDataBase64));
        return {
            status: statusCode == 200 && resp.status === 'ok' ? 'UP':'DOWN',
            latency: responseTime,
        }
        })