- name: OkBookmarks
  description: A free bookmark manager that lets you save and search your bookmarks in the cloud.
  tag: "okbookmarks"
  image: "https://okbookmarks.com/assets/img/extension_icon128.png"
  api:
      method: GET
      url: https://okbookmarks.com
- name: Earth
  description: Our blue planet
  tag: "earth"
  defaultStatus: "UP"
  image: "/earth.png"
- name: Frogment
  description: A free openAPI spec editor and linter that breaks down your spec into fragments to make editing easier and more intuitive. Visit https://www.frogment.com
  tag: "frogment"
  image: "/frogment.png"
  api:
      method: GET
      url: https://www.frogment.com
  alerts:
    DOWN: 
      failureThreshold: 5
      successThreshold: 2
      createIncident: false
      description: "Write a description here please"
      triggers:
        - MyWebhook
        - Discord Test
- name: CNAME Lookup
  description: Monitor example showing how to lookup CNAME record for a domain. The site www.rajnandan.com is hosted on GitHub Pages.
  tag: "cname-rajnandan"
  image: "https://www.rajnandan.com/assets/images/me.jpg"
  defaultStatus: "UP"
  dns:
      host: "www.rajnandan.com"
      lookupRecord: "CNAME"
      nameServer: "8.8.8.8"
      matchType: "ANY" # ANY, ALL
      values:
          - "rajnandan1.github.io"
- name: "Frogment APP Ping"
  description: "Ping www.frogment.app"
  image: https://www.frogment.app/icons/Square107x107Logo.png
  tag: "pingFrogmentApp"
  defaultStatus: "UP"
  ping:
    hostsV4:
    - "www.frogment.app"